language: python

python: "2.6"

env:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py32
    - TOXENV=py33
    - TOXENV=cov

branches:
    only:
        - master
        - develop

install: pip install --quiet --use-mirrors tox

script: tox

after_script:
    - if [ $TOXENV == "cov" ]; then
        pip install --quiet --use-mirrors coveralls;
        coveralls;
      fi
